[package]
name = "gdscript-checker"
description = "Type checker and linter for GDScript"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gdscript-core = { path = "../core" }
gdscript-parser = { path = "../parser" }
tree-sitter = { workspace = true }
