name: Develop CI

run-name: PR CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches-ignore:
      - main

permissions:
  contents: read

env:
  CARGO_HOME: /home/github-runner/cargo-cache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: fmt
    runs-on: [self-hosted, catfood]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: cargo fmt
        run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: [self-hosted, catfood]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: cargo clippy
        run: cargo clippy -- -D warnings

  test:
    name: test
    runs-on: [self-hosted, catfood]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: cargo test
        run: cargo test

  vscode-extension:
    name: vscode-extension
    runs-on: [self-hosted, catfood]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm ci
        working-directory: editors/vscode
        run: npm ci

      - name: Typecheck
        working-directory: editors/vscode
        run: npm run typecheck

      - name: Compile
        working-directory: editors/vscode
        run: npm run compile

  slack-notification:
    runs-on: [self-hosted, catfood]
    if: always()
    needs:
      - fmt
      - clippy
      - test
      - vscode-extension
    steps:
      - name: Post a message in a channel
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v2.1.1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
